spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:postgresql://database-1.cvyhsoweumof.eu-central-1.rds.amazonaws.com/postgres
    username: postgres
    password: postgres

  data:
    mongodb:
      uri: mongodb://localhost:27017/off

  mail:
    host: smtp.gmail.com
    port: 587
    username: flybookingprojekt@gmail.com
    password: aB1234567

    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
            required: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 864000000

